spring:
  application:
    name: login-service

  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true